INSERT INTO TB_CATEGORIA(NOME) VALUES('Informática');
INSERT INTO TB_CATEGORIA(NOME) VALUES('Escritório');

INSERT INTO TB_PRODUTO(NOME, PRECO) VALUES('Computador', 2000.00);
INSERT INTO TB_PRODUTO(NOME, PRECO) VALUES('Impressora', 800.00);
INSERT INTO TB_PRODUTO(NOME, PRECO) VALUES('Mouse', 80.00);

INSERT INTO PRODUTO_CATEGORIA(PRODUTO_ID, CATEGORIA_ID) VALUES(1, 1);
INSERT INTO PRODUTO_CATEGORIA(PRODUTO_ID, CATEGORIA_ID) VALUES(2, 1);
INSERT INTO PRODUTO_CATEGORIA(PRODUTO_ID, CATEGORIA_ID) VALUES(3, 1);
INSERT INTO PRODUTO_CATEGORIA(PRODUTO_ID, CATEGORIA_ID) VALUES(2, 2);