INSERT INTO TB_CATEGORIA(NOME) VALUES('Informática');
INSERT INTO TB_CATEGORIA(NOME) VALUES('Escritório');

INSERT INTO TB_PRODUTO(NOME, PRECO) VALUES('Computador', 2000.00);
INSERT INTO TB_PRODUTO(NOME, PRECO) VALUES('Impressora', 800.00);
INSERT INTO TB_PRODUTO(NOME, PRECO) VALUES('Mouse', 80.00);

INSERT INTO TB_PRODUTO_CATEGORIA(PRODUTO_ID, CATEGORIA_ID) VALUES(1, 1);
INSERT INTO TB_PRODUTO_CATEGORIA(PRODUTO_ID, CATEGORIA_ID) VALUES(2, 1);
INSERT INTO TB_PRODUTO_CATEGORIA(PRODUTO_ID, CATEGORIA_ID) VALUES(2, 2);
INSERT INTO TB_PRODUTO_CATEGORIA(PRODUTO_ID, CATEGORIA_ID) VALUES(3, 1);

INSERT INTO TB_ESTADO(NOME) VALUES ('Minas Gerais');
INSERT INTO TB_ESTADO(NOME) VALUES ('São Paulo');

INSERT INTO TB_CIDADE(NOME, ESTADO_ID) VALUES ('Uberlândia', 1);
INSERT INTO TB_CIDADE(NOME, ESTADO_ID) VALUES ('São Paulo', 2);
INSERT INTO TB_CIDADE(NOME, ESTADO_ID) VALUES ('Campinas', 2);